package com.cinemayan.catalog.domain.content;

public enum ContentWarning {
    GRAPHIC_VIOLENCE,
    MILD_VIOLENCE,
    WAR_VIOLENCE,
    DOMESTIC_ABUSE,
    CHILD_ABUSE,
    ANIMAL_CRUELTY,
    NUDITY,
    SEXUAL_CONTENT,
    EATING_DISORDERS,
    FLASHING_LIGHTS,
    JUMP_SCARES,
    DISTURBING_CONTENT,
    DISCRIMINATORY_LANGUAGE,
    MILD_SEXUAL_CONTENT,
    STRONG_LANGUAGE,
    MILD_LANGUAGE,
    DRUG_USE,
    ALCOHOL_USE,
    TOBACCO_USE,
    SUICIDE_SELF_HARM,
    MENTAL_HEALTH_THEMES
}
