package com.cinemayan.catalog.domain.content;

public enum CrewRole {
    DIRECTOR,
    ASSISTANT_DIRECTOR,
    SCREENPLAY_WRITER,
    STORY_WRITER,
    NOVEL_AUTHOR,
    PRODUCER,
    EXECUTIVE_PRODUCER,
    CO_PRODUCER,
    LINE_PRODUCER,
    DIRECTOR_OF_PHOTOGRAPHY,
    CAMERA_OPERATOR,
    PRODUCTION_DESIGNER,
    ART_DIRECTOR,
    SET_DECORATOR,
    COSTUME_DESIGNER,
    EDITOR,
    VISUAL_EFFECTS_SUPERVISOR,
    COLORIST,
    COMPOSER,
    SOUND_DESIGNER,
    MUSIC_SUPERVISOR,
    ANIMATION_DIRECTOR,
    CHARACTER_DESIGNER,
    SERIES_DIRECTOR,
    STORYBOARD_ARTIST
}
